<h1><?php echo $this->translate('System Configuration') ?></h1>
<div class="row">
    <?php if (!$this->config_dir_is_writable) : ?>
        <div class="col-md-12">
            <div class="alert alert-danger">
                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<?php
                echo sprintf($this->translate('The directory %s is not writable. Please make sure the webserver has write access!'), $this->config_dir)
                ?>
            </div>
        </div>
    <?php endif; ?>
    <?php if (!$this->config_is_writable) : ?>
        <div class="col-md-12">
            <div class="alert alert-danger">
                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<?php
                echo sprintf($this->translate('The ginger config file: %s in %s is not writable. Please make sure the webserver has write access!'), $this->config_file_name, $this->config_dir)
                ?>
            </div>
        </div>
    <?php endif; ?>
    <?php if (!$this->gingerConfig->isConfigured()) : ?>
        <div class="col-md-12">
            <div class="alert alert-warning">
                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<?php echo sprintf(
                    $this->translate('No configuration found for Ginger. Would you like to %screate one%s?'),
                    '<a href="'.$this->url('system_config/ginger_set_up').'">', '</a>') ?>
            </div>
        </div>
    <?php else : ?>
        <div class="col-md-8">
            <div class="row">
                <table class="table table-hover">
                    <tr>
                        <td>
                            <p class="text-info text-btn-align"><strong>Ginger Node Name</strong></p>
                        </td>
                        <td>
                            <p id="config-node-name" class="text-btn-align"><strong><?php echo $this->gingerConfig->getNodeName() ?></strong></p>
                        </td>
                        <td>
                            <a id="btn-node-name" href="#" class="btn btn-default edit"><?php echo $this->translate('edit') ?></a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    <?php endif; //if is configured end ?>
</div>
<script type="text/javascript">
    var toggleBtn = function($btn) {
        if ($btn.hasClass('edit')) {
            $btn.toggleClass('edit', 'save').html('<?php echo $this->translate('save') ?>');
        } else {
            $btn.toggleClass('edit', 'save').html('<?php echo $this->translate('edit') ?>');
        }
    };

    $(function() {
        $('#btn-node-name').click(function (e) {
            e.preventDefault();

            var $btn = $('#btn-node-name'), $nodeNameConfig = $('#config-node-name'),
            nodeName = '', oldNodeName = '';

            if ($btn.hasClass('edit')) {
                nodeName = $nodeNameConfig.children('strong').html();
                var $input = $('<input>').attr('type', 'text').addClass('form-control')
                    .val(nodeName)
                    .data('old-val', nodeName);

                $nodeNameConfig.removeClass('text-btn-align');

                $nodeNameConfig.html($input);

                toggleBtn($btn);
            } else {
                nodeName = $nodeNameConfig.children('input').val();
                oldNodeName = $nodeNameConfig.children('input').data('old-val');
                $nodeNameConfig.addClass('text-btn-align').html('<strong>'+nodeName+'</strong>');
                toggleBtn($btn);

                if (nodeName != oldNodeName) {
                    $.postJSON('<?php echo $this->url('system_config/change_node_name') ?>', {node_name : nodeName})
                        .done(function (data) {
                            $.notify('Node Name <?php echo $this->translate('successfully changed') ?>', 'success')
                        })
                        .fail($.failNotify);
                }
            }
        })
    })
</script>