<h1><?php echo $this->translate('System Configuration') ?></h1>
<hr>
<div class="row">
    <?php if (!$this->config_dir_is_writable) : ?>
        <div class="col-md-12">
            <div class="alert alert-danger">
                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<?php
                echo sprintf($this->translate('The directory %s is not writable. Please make sure the webserver has write access!'), $this->config_dir)
                ?>
            </div>
        </div>
    <?php endif; ?>
    <?php if (!$this->config_is_writable) : ?>
        <div class="col-md-12">
            <div class="alert alert-danger">
                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<?php
                echo sprintf($this->translate('The processing config file: %s in %s is not writable. Please make sure the webserver has write access!'), $this->config_file_name, $this->config_dir)
                ?>
            </div>
        </div>
    <?php endif; ?>
    <?php if (!$this->processingConfig->isConfigured()) : ?>
        <div class="col-md-12">
            <div class="alert alert-warning">
                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<?php echo sprintf(
                    $this->translate('No configuration found for prooph processing. Would you like to %screate one%s?'),
                    '<a href="'.$this->url('system_config/processing_set_up').'">', '</a>') ?>
            </div>
        </div>
    <?php else : ?>
        <div class="col-md-12">
            <system-configurator></system-configurator>
        </div>
    <?php endif; //if is configured end ?>
</div>
<?php
if ($this->gingerConfig->isConfigured()) {

//Bootstrap riot app
$this->inlineScript()->captureStart();

$nodeName = $this->gingerConfig->getNodeName();

echo <<<JS
window.SysConf = Ginger.App.create(
    {
        node_name : '$nodeName'
    }
);

$(function () {
    SysConf.bootstrap("system-configurator").ready();
});
JS;
    $this->inlineScript()->captureEnd();
    $this->inlineScript()->prependFile($this->basePath() . '/js/system-config/app.js');
}
?>
