<div id="process_name_container"></div>
<div if="{ processNotFound }" class="alert alert-danger">
    <?php echo $this->translate('The process could not be found. Please go back to the overview and try again or contact the support for help.') ?>
</div>
<div if="{ ! processNotFound }" class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
        <div class="list-group">
            <a each="{ process.tasks }" href="#processes/{ parent.process.id }/show/tasks/{ id }/update" class="list-group-item"><div id="task_desc_{ id }"></div></a>
            <a href="#processes/{ process.id }/show/tasks/create" class="list-group-item list-group-item-success text-uppercase text-center"><strong><?php echo $this->translate('add task') ?></strong></a>
        </div>
    </div>
</div>
<script type="text/javascript">
    function (context) {

        var self = this;

        var process = _.findWhere(context.app.processes, {id : context.app.routeMatch.index});

        this.processNotFound = ! process;

        this.process = process || {name : '<?php echo $this->translate('Process Not Found')  ?>', tasks : []};


        this.on("mount", function () {
            context.app.renderInto(self, "#process_name_container", "process-name", {process : this.process});
            _.each(this.process.tasks, function(task) {
                context.app.renderInto(self, "#task_desc_" + task.id, "task-desc", {task : task});
            });
        });
    }
</script>