<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <h3 class="text-center">{ process.name }</h3>
    </div>
    <div class="col-xs-2">
        <span class="pull-right"><a href="#" class="btn btn-default btn-h3"><?php echo $this->translate('edit') ?></a>&nbsp;&nbsp;<process-play process="{ process }" app="{ app }"></process-play></span>
    </div>
</div>
<hr>
<script type="text/javascript">
    function (context) {
        if (context.process) {
            this.process = context.process;
        } else {
            this.process = { name : "<?php echo $this->translate('Unknown')  ?>" };
        }

        this.isCollectDataProcess = function () {
            if (! this.process.start_message) return false;

            return this.process.start_message.message_type == '<?php echo \Prooph\Processing\Message\MessageNameUtils::COLLECT_DATA  ?>';
        }
    }
</script>