<button name="run_process" class="{ btn: true, btn-default: true, btn-h3: true, disabled: ! isCollectDataProcess() }" onclick="{ runProcess }"><span class="glyphicon glyphicon-play"></span></button>
<script type="text/javascript">
    function (context) {
        var self = this,
            loadStartMessageRetries = {};

        this.process = context.process;

        this.isCollectDataProcess = function () {
            if (! this.process.start_message) return false;

            return this.process.start_message.message_type == '<?php echo \Ginger\Message\MessageNameUtils::COLLECT_DATA  ?>';
        }

        this.loadStartMessage = function (location) {
            if (! loadStartMessageRetries[location]) loadStartMessageRetries[location] = 0;

            if (loadStartMessageRetries[location] > 3) {
                $.appErrorNotify(s.sprintf('<?php echo $this->translate('Unable to load process id from: %s. Please contact the support!')  ?>', location));
                return;
            }

            $.getJSON(location).then(function (data) {
                var message = data.message;

                if (! message.process_id) {
                    loadStartMessageRetries[location]++;
                    window.setTimeout(function () {
                        self.loadStartMessage(location);
                    }, 3000);
                    return;
                }

                window.location.href = '<?php echo $this->url('monitor/process_details')  ?>' + message.process_id;
            }, $.failNotify);
        }

        this.runProcess = function () {
            if (! this.isCollectDataProcess()) return false;

            var command = {
                collect_data_trigger : {
                    ginger_type : this.process.start_message.ginger_type
                }
            };

            $(this.run_process).addClass("active disabled").find("span").toggleClass("glyphicon-play glyphicon-dashboard");

            $.postJSON('<?php echo $this->url('processor_proxy/api/collect_data_triggers')  ?>', command)
                .then(function (data, status, xhr) {
                    var messageLocation = xhr.getResponseHeader('Location');

                    if (! messageLocation) {
                        $.appErrorNotify('<?php echo $this->translate('Location header for start message is missing. Please contact the support!')  ?>');
                        return;
                    }

                    self.loadStartMessage(messageLocation);
                }, $.failNotify);
        }
    }
</script>