<?php
/*
 * This file was auto generated by SqlConnector\Service\TableConnectorGenerator.
 * (c) prooph software GmbH <contact@prooph.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Application\DataType\SqlConnector\TestDb;

use Ginger\Type\AbstractCollection;
use Ginger\Type\Description\Description;
use Ginger\Type\Description\NativeType;
use Ginger\Type\Prototype;

class TestDataCollection extends AbstractCollection
{
    /**
     * Returns the prototype of the items type
     *
     * A collection has always one property with name item representing the type of all items in the collection.
     *
     * @return Prototype
     */
    public static function itemPrototype()
    {
        return TestData::prototype();
    }

    /**
     * @return Description
     */
    public static function buildDescription()
    {
        return new Description("TestData List", NativeType::COLLECTION, false);
    }
}