<?php if (! $this->ginger_is_configured) : ?>
    <div class="alert alert-warning">
        <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<?php echo $this->translate('Ginger runs currently in default mode') ?>!
    </div>
    <p class="text-center"><a href="<?php echo $this->url('system_config') ?>" class="btn btn-success"><?php echo $this->translate('Set up the system') ?></a></p>
<?php endif; ?>