<div class="row">
    <div class="col-md-12">
        <h2><?php echo $this->translate('Environment')?></h2>
        <system-node-name app="{ app }"></system-node-name>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2>Message Queue</h2>
        <system-message-queue app="{ app }"></system-message-queue>
    </div>
</div>
<script type="text/javascript">
    function (context) {
        this.app = context.app;
    }
</script>