<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Process Manager Tests</title>
    <?php echo $this->headLink()
        ->prependStylesheet($this->basePath() . '/css/qunit.css')
        ?>
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/global.settings.js')
        ->prependFile($this->basePath() . '/js/notify.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
</head>
<body>
<?php echo $this->content; ?>
    <div id="qunit"></div>
    <div id="qunit-fixture"></div>
<?php echo $this->inlineScript()
    ->prependFile($this->basePath() . '/js/ember.helpers.js')
    ->prependFile($this->basePath() . '/js/i18n-plurals.js')
    ->prependFile($this->basePath() . '/js/i18n.js')
    ->prependFile($this->basePath() . '/js/ember.data.js')
    ->prependFile($this->basePath() . '/js/ember.js')
    ->prependFile($this->basePath() . '/js/handlebars.js')
    ->prependFile($this->basePath() . '/js/qunit.js')
    ->appendFile($this->basePath() . '/js/process-config/app-test.js')
?>
</body>
</html>