<script type="text/x-handlebars" data-template-name="process" xmlns="http://www.w3.org/1999/html">
    <h3 class="text-center">{{model.name}}&nbsp;&nbsp;&nbsp;{{process-status model}}</h3>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <h4><?php echo $this->translate('Started') ?>:&nbsp;&nbsp;&nbsp;{{started_at}}</h4>
            <h4><?php echo $this->translate('Finished') ?>:&nbsp;{{finished_at}}</h4>
        </div>
    </div>
    <h4><?php echo $this->translate('Task List') ?></h4>
    <div class="list-group text-center">
        {{#each task in model.tasks}}
            <div class="task">
                <a href="#" class="list-group-item task-summary">
                    {{task-desc task}} <div class="pull-right">{{task-status task}}</div>
                </a>
                <div class="task-details text-left well well-large hidden">
                    <div class="row">
                        <div class="col-md-12">
                            <h5><?php echo $this->translate('Logged Events') ?></h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="list-group">
                                {{#each event in task.events}}
                                    {{render "taskEvent" event}}
                                {{else}}
                                    <div class="list-group-item text-warning">
                                        <?php echo $this->translate('No events logged') ?>&nbsp;<span class="glyphicon glyphicon-warning-sign"></span>
                                    </div>
                                {{/each}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {{else}}
            <div class="list-group-item text-warning">
                <?php echo $this->translate('No tasks found for process!') ?>
            </div>
        {{/each}}
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <a {{bind-attr href="configUrl"}} class="btn btn-default pull-right"><?php echo $this->translate('Edit') ?></a>
        </div>
    </div>
</script>
<script type="text/x-handlebars" data-template-name="taskEvent">
<div {{bind-attr class=":list-group-item :event-container isInfoEvent:text-info isWarningEvent:text-warning isErrorEvent:text-danger"}}>
    <div class="row">
        <div class="col-xs-12 col-md-8">
            {{description}}
        </div>
        <div class="col-xs-10 col-md-3">
            {{occurredOn}}
        </div>
        <div class="col-xs-2 col-md-1">
            {{#if isLogEvent}}
                <a href="#" class="btn btn-sm btn-default log-message-details-toggle"><span class="glyphicon glyphicon-arrow-down"></span></a>
            {{/if}}
        </div>
    </div>
    {{#if isLogEvent}}
    <div class="row log-message-details hidden">
        <div class="col-md-12">
            {{logMessageDetails}}
        </div>
    </div>
    {{/if}}
</div>
</script>