<?php
$statusToClass = function($status, $textClass = true) {
    switch ($status) {
        case \Gingerwork\Monitor\Model\ProcessLogger::STATUS_RUNNING:
            return ($textClass)? 'warning' : 'glyphicon-flash';
        case \Gingerwork\Monitor\Model\ProcessLogger::STATUS_SUCCEED:
            return ($textClass)? 'success'  : 'glyphicon-ok';
        case \Gingerwork\Monitor\Model\ProcessLogger::STATUS_FAILED:
            return ($textClass)? 'danger' :  'glyphicon-remove';
    }
};

$dateFormat = function($dateTimeStr) {
    if (is_null($dateTimeStr)) {
        return '-';
    }

    return $this->dateFormat(
        \DateTime::createFromFormat(\DateTime::ISO8601, $dateTimeStr),
        IntlDateFormatter::MEDIUM,
        IntlDateFormatter::MEDIUM,
        $this->plugin('translate')->getTranslator()->getLocale()
    );
}
?>
<div class="list-group">
    <?php foreach ($this->processes as $process) : ?>
        <a href="<?php echo $this->url('monitor/process_details', ['process_id' => $process['process_id']]) ?>"
           class="list-group-item list-group-item-text">
            <div class="row">
                <div class="col-xs-6"><?php echo $process['process_name'] ?></div>
                <div class="col-xs-2"><?php echo $this->translate('finished at') ?>:</div>
                <div class="col-xs-3"><?php echo $dateFormat($process['finished_at']) ?></div>
                <div class="col-xs-1 text-<?php echo $statusToClass($process['status']) ?>">
                    <span class="glyphicon <?php echo $statusToClass($process['status'], false) ?>"></span>
                </div>
            </div>
        </a>
    <?php endforeach; ?>
</div>