<script type="text/x-handlebars" data-template-name="sqlconnector/pm-metadata-config">
<h5><?php echo $this->translate('Filter') ?></h5>
{{#if isSingleResultType}}
    <div class="checkbox">
        <label for="filter_identifier">
            {{input type="checkbox" name="filter_identifier" checked=metadata.identifier}} <?php echo $this->translate('Filter By Identifier') ?>
        </label>
    </div>
{{/if}}
{{#unless isIdentifier}}
    {{#each filterItem in metadataFilterList}}
        <form class="form-inline">
            <div class="form-group">
                {{input type="text" name="filter_column" class="form-control form-control-inline-4" value=filterItem.column readonly=true}}
            </div>&nbsp;&nbsp;
            <div class="form-group">
                {{input type="text" name="filter_operand" class="form-control form-control-inline-3" value=filterItem.operand readonly=true}}
            </div>&nbsp;&nbsp;
            <div class="form-group">
                {{input type="text" name="filter_value" class="form-control form-control-inline-4" value=filterItem.value readonly=true}}
            </div>&nbsp;&nbsp;
            <button class="btn btn-sm btn-danger" {{action "removeFilter" filterItem}}><span class="glyphicon glyphicon-remove"></span></button>
        </form>
    {{/each}}
    <br>
    <form class="form-inline">
        <div class="form-group">
            {{view "select" id="first-filter-input" class="form-control form-control-inline-4"
            prompt="- <?php echo $this->translate('Property') ?> -"
            content=availableDataTypeProperties
            value=tempFilter.column}}
        </div>&nbsp;&nbsp;
        <div class="form-group">
            {{view "select" class="form-control form-control-inline-3"
            prompt="- <?php echo $this->translate('Operand') ?> -"
            content=availableOperands
            value=tempFilter.operand
            }}
        </div>&nbsp;&nbsp;
        <div class="form-group">
            {{input type="text" name="filter_value" class="form-control form-control-inline-4" value=tempFilter.value placeholder="<?php echo $this->translate('Value') ?>"}}
        </div>&nbsp;&nbsp;
        <button class="btn btn-sm btn-success" {{action "addFilter"}}><span class="glyphicon glyphicon-plus"></span></button>
        {{input type="hidden" name="filter_key" value=autoFilterKey}}
    </form>
    {{#if isDuplicateColumn}}
        <br>
        <p class="alert alert-danger"><?php echo $this->translate('Your filter would never match entries, because you try to add the same property twice. This is only possible when defining a -between- filter, but your operands do not match, too. Please correct your choice.') ?></p>
    {{/if}}
    {{#unless isSingleResultType}}
        <hr>
        <form class="form-inline">
            <div class="form-group">
                <label for="limit">Limit</label>
                {{input type="text" name="limit" class="form-control form-control-inline-2" value=metadata.limit placeholder="Limit"}}
            </div>&nbsp;&nbsp;
            <div class="form-group">
                <label for="offset">Offset</label>
                {{input type="text" name="offset" class="form-control form-control-inline-2" value=metadata.offset placeholder="Offset"}}
            </div>
        </form>
        <br>
        <form class="form-inline">
            <div class="form-group text-">
                <label for="order_by" class="text-btn-align">Order By</label>&nbsp;&nbsp;
                {{#each order in orderByArr}}
                    <span class="text-btn-align"><big>{{order}}</big></span>&nbsp;<button class="btn btn-xs btn-danger" {{action "removeOrderBy" order}}><span class="glyphicon glyphicon-remove"></span></button>
                {{/each}}

                {{view "select" class="form-control form-control-inline-2"
                prompt="- <?php echo $this->translate('Property') ?> -"
                content=availableOrderByProperties
                value=tempOrderByProp}}
                &nbsp;&nbsp;
                {{view "select" class="form-control form-control-inline-2"
                prompt="- <?php echo $this->translate('Order') ?> -"
                content=orderOptions
                value=tempOrderByOrder}}
                &nbsp;&nbsp;
                <button class="btn btn-sm btn-success" {{action "addOrderBy"}}><span class="glyphicon glyphicon-plus"></span></button>
            </div>
        </form>
    {{/unless}}
{{/unless}}
</script>