<script type="text/x-handlebars" data-template-name="sqlconnector/pm-metadata-config">
<h5><?php echo $this->translate('Filter') ?></h5>
{{#if isSingleResultType}}
    <div class="form-group">
        <label for="filter_identifier"><?php echo $this->translate('Filter By Identifier') ?>?</label>
        {{input type="checkbox" name="filter_identifier" checked=metadata.identifier}}
    </div>
{{/if}}
</script>