<div class="row text-center">
    <div id="app" class="col-md-12">
        <h1><?php echo $this->translate('File Connector Manager') ?></h1>
        <script type="text/x-handlebars" data-template-name="file-manager">
            {{outlet}}
        </script>
    </div>
</div>
<?php

echo $this->partial('file-connector/file-manager/partial/manager-index');

//Bootstrap ember app
$this->inlineScript()->captureStart();

$apiUrl = ltrim($this->url('file_connector/api'), '/');

$shortLocale = explode("_", $this->plugin('translate')->getTranslator()->getLocale())[0];

$clientTranslations = json_encode([
    'file_manager' => [
        'label' => $this->translate('File Manager')
    ]
]);
echo <<<JS
window.App = Ember.Application.create({
    rootElement : '#app'
});

DS.RESTAdapter.reopen({
  namespace : '{$apiUrl}'
});

Em.I18n.locale = '{$shortLocale}';

Em.I18n.translations = $clientTranslations;

App.Object = Ember.Object.extend(Em.Serializable);
JS;
$this->inlineScript()->captureEnd();
//$this->inlineScript()->appendFile($this->basePath() . '/js/file-connector/app.js');
?>
