<div class="row text-center">
    <div class="col-md-12">
        <h1 class="text-center"><?php echo $this->translate('File Manager') ?></h1>
        <file-manager></file-manager>
    </div>
</div>
<?php

$this->partial('file-connector/file-manager/partial/sidebar-left');

//Bootstrap ember app
$this->inlineScript()->captureStart();

//$apiUrl = ltrim($this->url('file_connector/api'), '/');

$fileConnectors = json_encode($this->file_connectors);
$availableProcessingTypes = json_encode($this->available_processing_types);
$availableFileTypes  = json_encode($this->available_file_types);
$availableSystemConnectors = json_encode($this->system_connectors);

echo <<<JS
window.FM = Prooph.Link.App.create(
    {
        connectors : {$fileConnectors},
        processingTypes : {$availableProcessingTypes},
        fileTypes : {$availableFileTypes},
        systemConnectors : {$availableSystemConnectors}
    }
);

$(function () {
    FM.bootstrap("file-manager").ready();
});
JS;
$this->inlineScript()->captureEnd();
$this->inlineScript()->prependFile($this->basePath() . '/js/file-connector/app.js');
?>
