<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('prooph LINK')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        /**
         * Link globally required CSS files.
         * The default layout uses the Bootswatch Slate template: https://bootswatch.com/slate/
         */
        echo $this->headLink(/*array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')*/)
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.slate.min.css')
        ?>

        <!-- Scripts -->
        <?php
        /**
         * Link globally required javascript libs
         */
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/global.settings.js')
            ->prependFile($this->basePath() . '/js/q.js')
            ->prependFile($this->basePath() . '/js/notify.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/underscore.string.js')
            ->prependFile($this->basePath() . '/js/lodash.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
        <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo 'prooph LINK' ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php //add navbar links here ?>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <?php //This icon can be manipulated by JS. The Javascript ticker included in prooph/link-app-core changes color of the icon when the js ticker is running or a request failed ?>
                        <li id="js_ticker_status" class="navbar-text navbar-text-lg"><span class="glyphicon glyphicon-dashboard" title="Javascript Ticker"></span></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="row">
            <div class="hidden-xs col-sm-3 col-md-2">
                <div id="sidebar-left" data-spy="affix" data-offset-top="60">
                    <?php if (isset($this->sidebar_left)) echo $this->sidebar_left; ?>
                </div>
            </div>
            <div class="col-sm-7 col-md-8">
                <?php echo $this->content; ?>
                <hr>
                <footer>
                    <p>&copy; 2014 - <?php echo date('Y') ?> by prooph software GmbH. <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
            </div>
            <div class="col-sm-2 col-md-2">
                <?php if (isset($this->sidebar_right)) echo $this->sidebar_right; ?>
            </div>
        </div>
        <?php echo $this->inlineScript()
            ->prependFile($this->basePath() . '/js/prooph.link.riot.app.js')
            ->prependFile($this->basePath() . '/js/riot.js')
        ?>
        <?php
        /**
         * The javascript ticker view helper is provided by prooph/link-app-core.
         * You should remove the line, if you don't want to use the js ticker functionality
         */
        echo $this->javascriptTicker();
        ?>
    </body>
</html>
