<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Ginger Workflow Management System')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(/*array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')*/)
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.slate.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/global.settings.js')
            ->prependFile($this->basePath() . '/js/notify.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
        <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo 'Ginger IWM' ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">

                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="row">
            <div class="hidden-xs col-sm-3 col-md-2">
                <div id="sidebar-left" data-spy="affix" data-offset-top="60">
                    <?php if (isset($this->sidebar_left)) echo $this->sidebar_left; ?>
                </div>
            </div>
            <div class="col-sm-7 col-md-8">
                <?php echo $this->content; ?>
                <hr>
                <footer>
                    <p>&copy; 2014 - <?php echo date('Y') ?> by prooph software GmbH. <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
            </div>
            <div class="col-sm-2 col-md-2">
                <?php if (isset($this->sidebar_right)) echo $this->sidebar_right; ?>
            </div>
        </div>
        <?php echo $this->inlineScript()
            ->prependFile($this->basePath() . '/js/ember.helpers.js')
            ->prependFile($this->basePath() . '/js/i18n-plurals.js')
            ->prependFile($this->basePath() . '/js/i18n.js')
            ->prependFile($this->basePath() . '/js/ember.data.js')
            ->prependFile($this->basePath() . '/js/ember.js')
            ->prependFile($this->basePath() . '/js/handlebars.js')
        ?>
    </body>
</html>
