<script type="text/x-handlebars" data-template-name="processes/create">
    <h2><?php echo $this->translate('New Process') ?></h2>
    <hr>
    <div class="row">
        <div class="col-sm-12 col-md-8 col-md-offset-2">
            <div class="row">
                <div class="col-md-6">
                    <div {{bind-attr class=":form-group :has-feedback isAProcessSelected:has-success"}}>
                        {{view "select" class="form-control form-control-with-desc"
                        prompt="- <?php echo $this->translate('Process Type') ?> -"
                        content=processTypes
                        optionValuePath="content.value"
                        optionLabelPath="content.label"
                        value=process_type}}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="text-info process-desc">
                        {{#if isNonProcessSelected}}
                        <?php echo $this->translate('Choose a process type. If you are unsure which type to select go through the list and you will get a description for each type.') ?>
                        {{/if}}
                        {{#if isLinearProcess}}
                        <?php echo $this->translate('The linear process triggers all tasks in a sequence. The previous task must be finished before the next task will start.') ?>
                        {{/if}}
                        {{#if isForeachProcess}}
                        <?php echo $this->translate('The foreach process only works with collections. It passes each item of the collection to its defined task list. The tasks are triggered in parallel.') ?>
                        {{/if}}
                    </div>
                </div>
            </div>
            <h3><?php echo $this->translate('Process Trigger') ?></h3>
            <hr>
            <div class="row">
                <div class="col-md-6">
                    <div {{bind-attr class=":form-group :has-feedback isAMessageTypeSelected:has-success"}}>
                    {{view "select" class="form-control form-control-with-desc"
                    prompt="- <?php echo $this->translate('Message Type') ?> -"
                    content=messageTypes
                    optionValuePath="content.value"
                    optionLabelPath="content.label"
                    value=message_type}}
                    </div>
                    <div {{bind-attr class=":form-group :has-feedback isGingerTypeSelected:has-success"}}>
                    {{data-type-select class="form-control form-control-with-desc"
                    prompt="- <?php echo $this->translate('Data  Type') ?> -"
                    content=gingerTypes
                    optionValuePath="content.value"
                    optionLabelPath="content.label"
                    value=ginger_type}}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="well well-lg text-info process-desc">
                        {{#if isNotGingerTypeSelectFocused}}
                        {{#if isNonMessageSelected}}
                        <?php echo $this->translate('Each process is triggered by a workflow message. Such a message consists of two parts: a message type and a data type.') ?>
                        {{/if}}
                        {{#if isCollectDataMessage}}
                        <?php echo $this->translate('A collect-data message is useful when the first task of the process should collect data from a source system.') ?>
                        {{/if}}
                        {{#if isDataCollectedMessage}}
                        <?php echo $this->translate('A data-collected message is useful when a process should be started automatically as soon as such a message is received.') ?>
                        {{/if}}
                        {{/if}}
                        {{#if gingerTypeSelectFocused}}
                        <?php echo $this->translate('Data types are provided by system connectors or plugins. They define the structures a connected system can provide or process.') ?>
                        {{/if}}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <buton class="btn btn-success pull-right" {{action "createProcess"}} {{bind-attr disabled=isNotValid}}><?php echo $this->translate('Create Process') ?></butoon>
                </div>
            </div>
        </div>
    </div>
</script>