<script type="text/x-handlebars" data-template-name="process">
    <h3>{{model.name}} {{#link-to 'process.edit' model class="btn btn-default pull-right"}}<?php echo $this->translate('edit') ?>{{/link-to}}</h3>
    <hr>
    <div class="row">
        <div id="left-panel" class="col-md-12">
            {{outlet leftpanel}}
        </div>
    </div>
</script>
<script type="text/x-handlebars" data-template-name="process/tasks">
    <div class="list-group">
        {{#each task in model.tasks}}
            {{#link-to 'task' task class="list-group-item"}}{{task-desc task}}{{/link-to}}
        {{/each}}
        {{#link-to 'tasks.create' class="list-group-item list-group-item-success text-center text-uppercase"}}<strong><?php echo $this->translate('Add Task') ?></strong>{{/link-to}}
    </div>
</script>
<script type="text/x-handlebars" data-template-name="process/edit">
    process edit {{model.name}}
</script>
<script type="text/x-handlebars" data-template-name="task">
    <h4>{{task-desc model}}</h4>
    <div class="alert-block text-info">
        <i><?php echo $this->translate('Note') ?>:&nbsp;<?php echo $this->translate('The process manager only suggests valid combinations.') ?></i>
    </div>
    <div {{bind-attr class=":form-group :has-feedback isATaskTypeSelected:has-success"}}>
        {{view "select" class="form-control form-control-with-desc"
        prompt="- <?php echo $this->translate('Task Type') ?> -"
        content=availableTaskTypes
        optionValuePath="content.value"
        optionLabelPath="content.label"
        value=task_type}}
    </div>
    {{#if isCollectDataTask}}
        <div {{bind-attr class=":form-group :has-feedback isASourceSelected:has-success"}}>
            {{view "select" class="form-control form-control-with-desc"
            prompt="- <?php echo $this->translate('Source') ?> -"
            content=availableSources
            optionValuePath="content.value"
            optionLabelPath="content.label"
            value=source}}
        </div>
        <div {{bind-attr class=":form-group :has-feedback isAGingerTypeSelected:has-success"}}>
            {{view "select" class="form-control form-control-with-desc"
            prompt="- <?php echo $this->translate('Data Type') ?> -"
            content=availableGingerTypes
            optionValuePath="content.value"
            optionLabelPath="content.label"
            value=ginger_type}}
        </div>
    {{/if}}
    {{#if isProcessDataTask}}
        <div {{bind-attr class=":form-group :has-feedback isATargetSelected:has-success"}}>
            {{view "select" class="form-control form-control-with-desc"
            prompt="- <?php echo $this->translate('Target') ?> -"
            content=availableTargets
            optionValuePath="content.value"
            optionLabelPath="content.label"
            value=model.target}}
        </div>
        <div {{bind-attr class=":form-group :has-feedback isAGingerTypeSelected:has-success"}}>
            {{view "select" class="form-control form-control-with-desc"
            prompt="- <?php echo $this->translate('Data Type') ?> -"
            content=availableGingerTypes
            optionValuePath="content.value"
            optionLabelPath="content.label"
            value=preferred_type}}
        </div>
    {{/if}}
    {{#if isManipulatePayloadTask}}
        <div {{bind-attr class=":form-group :has-feedback isManipulationScriptSelected:has-success"}}>
            {{view "select" class="form-control form-control-with-desc"
            prompt="- <?php echo $this->translate('Payload Manipulation Script') ?> -"
            content=manipulationScripts
            value=manipulation_script}}
        </div>
    {{/if}}
    {{#if showMetadata}}
        <div class="row metadata-block text-left">
            <div class="col-md-12">
                <h4><?php echo $this->translate('Metadata Configuration') ?></h4>
                {{view "metadata"}}
            </div>
        </div>
    {{/if}}
    <hr>
    <div class="row">
        <div class="col-md-12">
            <div class="pull-right">
                {{#link-to "tasks.index" class="btn btn-default" activeClass=""}}<?php echo $this->translate('cancel') ?>{{/link-to}}
                <button class="btn btn-success" {{action saveTask}} {{bind-attr disabled=isNotValid}}><?php echo $this->translate('save') ?></button>
            </div>
        </div>
    </div>
    {{#unless isNewTask}}
    <hr>
    <div class="well text-right">
        <h4 class="text-danger text-center"><?php echo $this->translate('Danger Zone') ?></h4>
        {{#link-to 'task.delete' model class="btn btn-danger"}}<?php echo $this->translate('Delete Task') ?>{{/link-to}}
    </div>
    {{/unless}}
</script>