<script type="text/x-handlebars" data-template-name="manager/index">
    <div class="row">
        <div class="col-md-12">
            <div id="processes" class="list-group">
                {{#each process in model}}
                {{#link-to 'process' process class="list-group-item text-center"}}<strong>{{process.name}}</strong>{{/link-to}}
                {{/each}}
            </div>
        </div>
    </div>
</script>