<?php
$numberOfConnectors = count($this->fileConnectors);
$message = $this->translatePlural('You\'ve one connector defined', 'You\'ve %s connectors defined', $numberOfConnectors);

if ($numberOfConnectors === 0) $numberOfConnectors = 'no';
?>
<ul class="list-group">
    <li class="list-group-item list-group-item-text text-info"><?php echo sprintf($message, $numberOfConnectors) ?>&nbsp;<span class="glyphicon glyphicon-<?php echo ($numberOfConnectors > 0)? 'ok' : 'ban-circle' ?> pull-right"></span></li>
</ul>
<p class="text-center"><a href="<?php echo $this->url('file_connector/configurator') ?>" class="btn btn-info"><?php echo $this->translate('configure connectors') ?></a></p>

