<script type="text/x-handlebars" data-template-name="connector/edit">
{{#if isNew}}
    <h2><?php echo $this->translate('New File Connector') ?></h2>
{{else}}
    <h2>{{name}}</h2>
{{/if}}
<hr>
<div class="row">
    <div class="col-sm-12 col-md-8 col-md-offset-2">
        <div {{bind-attr class=":form-group :has-feedback isDataTypeSelected:has-success :text-left"}}>
            <label for="data_type"><?php echo $this->translate('Choose data type for which you want to create a file connector.') ?></label>
            {{view "select" name="data_type" class="form-control"
            prompt="- <?php echo $this->translate('Data Type') ?> -"
            content=availableDataTypes
            optionValuePath="content.value"
            optionLabelPath="content.label"
            value=data_type}}
        </div>
        <div {{bind-attr class=":form-group :has-feedback isFileTypeSelected:has-success :text-left"}}>
            <label for="file_type"><?php echo $this->translate('Select the type the file will have.') ?></label>
            {{view "select" name="file_type" class="form-control"
            prompt="- <?php echo $this->translate('File Type') ?> -"
            content=availableFileTypes
            value=metadata.file_type}}
        </div>
        <div {{bind-attr class=":form-group :has-feedback isValidName:has-success isDuplicateName:has-error :text-left"}}>
            <label for="name"><?php echo $this->translate('Give your connector a unique name (or use the default)') ?></label>
            {{input type="text" name="name" class="form-control form-control" value=nameWithDefault placeholder="Name"}}
            {{#if isDuplicateName}}
                <br>
                <div class="alert alert-danger"><?php echo $this->translate('The connector name is already in use. Please choose another name') ?>!</div>
            {{/if}}
        </div>
        <div class="form-group text-left">
            <label><?php echo $this->translate('For what reason do you need the file') ?>?</label>
            <br>
            <button {{bind-attr class=":btn readable:btn-success:btn-default readable:active"}} {{action "toggleReadable"}}><?php echo $this->translate('import data') ?></button>&nbsp;&nbsp;&nbsp;
            <button {{bind-attr class=":btn writable:btn-success:btn-default writable:active"}} {{action "toggleWritable"}}><?php echo $this->translate('export data') ?></button>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-12">
                <div class="pull-right">
                    {{#link-to "connectors.index" class="btn btn-default" activeClass=""}}<?php echo $this->translate('cancel') ?>{{/link-to}}
                    {{#if isNew}}
                        <button class="btn btn-success" {{action "createConnector"}} {{bind-attr disabled=isNotValid}}><?php echo $this->translate('create connector') ?></button>
                    {{else}}
                        <button class="btn btn-success" {{action "saveConnector"}} {{bind-attr disabled=isNotValid}}><?php echo $this->translate('save') ?></button>
                    {{/if}}
                </div>
            </div>
        </div>
    </div>
</div>
</script>