<script type="text/x-handlebars" data-template-name="connectors/index">
    <div class="row">
        <div class="col-md-12">
            <div id="connectors" class="list-group">
                {{#each connector in model}}
                {{#link-to 'connector.edit' connector class="list-group-item text-center"}}<strong>{{connector.name}}</strong>{{/link-to}}
                {{/each}}
                {{#link-to 'connectors.create' class="list-group-item list-group-item-success text-center"}}<strong><?php echo strtoupper($this->translate('Add New Connector')) ?></strong>{{/link-to}}
            </div>
        </div>
    </div>
</script>