<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <h3 class="text-center">{ process.name }&nbsp;&nbsp;&nbsp;<span id="process_status"></span></h3>
    </div>
    <div class="col-xs-1"><a href="<?php echo $this->url('process_config/configurator') ?>#processes/{ process.id }" class="btn btn-default pull-right btn-h3"><?php echo $this->translate('Edit') ?></a></div>
</div>
<hr>
<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
        <h4><?php echo $this->translate('Started') ?>:&nbsp;&nbsp;&nbsp;{ process.started_at }</h4>
        <h4><?php echo $this->translate('Finished') ?>:&nbsp;{ process.finished_at }</h4>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
        <h4><?php echo $this->translate('Task List') ?></h4>
        <div class="list-group">
            <task-monitor each="{ process.tasks }" task="{ this }" app="{ parent.app }"></task-monitor>
            <div if="{ ! process.tasks.length }" class="list-group-item text-warning">
                <?php echo $this->translate('No tasks found for process!') ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function (context) {
        this.process = context.app.process;
        this.app = context.app;

        this.updateStatusIcon = function () {
            $(this.process_status).html(status_icon(this.process.status));
        }

        this.on("mount", function () {
            this.updateStatusIcon();
        });
    }
</script>