<?php if (count($this->processingConfig->getProcessDefinitions()) === 0) : ?>
    <div class="alert alert-warning">
        <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<?php echo $this->translate('No processes configured yet') ?>!
    </div>
    <p class="text-center"><a href="<?php echo $this->url('process_config/configurator') ?>#/create" class="btn btn-success"><?php echo $this->translate('create your first process') ?></a></p>
<?php else : ?>
    <?php
    $numberOfProcesses = count($this->processingConfig->getProcessDefinitions());
    $message = $this->translatePlural('You\'ve one process defined', 'You\'ve %s processes defined', $numberOfProcesses);
    ?>
    <ul class="list-group">
        <li class="list-group-item list-group-item-text text-info"><?php echo sprintf($message, $numberOfProcesses) ?>&nbsp;<span class="glyphicon glyphicon-ok pull-right"></span></li>
    </ul>
    <p class="text-center"><a href="<?php echo $this->url('process_config/configurator') ?>" class="btn btn-inverse"><?php echo $this->translate('view processes') ?>&nbsp;<span class="glyphicon glyphicon-eye-open"></span></a></p>
<?php endif; ?>
